### ISSUE TITLE
Your uniform is removed during rounds.

### ISSUE THREAD

**Issue by chris12902** [RubyStudios/Paintball-Tracker#6]
![image](https://cloud.githubusercontent.com/assets/8672692/7902832/2b4b2dec-0795-11e5-83ec-25dd1ef143fe.png)

**Comment by chris12902** [comment]
![image](https://cloud.githubusercontent.com/assets/8672692/7902887/35cb3238-0797-11e5-9c68-064716dd5f60.png)
This also occurs during CTF rounds.

**Comment by gamenew09** [comment]
Is it after respawns?

**Comment by chris12902** [comment]
No. It's also during round, when you spawn, and after you spawn.

**Comment by gamenew09** [comment]
Test online

**Comment by chris12902** [comment]
Seems to be fixed
