### ISSUE TITLE
Rayman Lobby Music plays in rounds

### ISSUE THREAD

**Issue by chris12902** [RubyStudios/Paintball-Tracker#9]
When playing in round, the Rayman lobby music will play because it is not properly stopped.

Easy fix:
line 903, make a line that causes all sounds in folder "LobbyMusic" in "Music" stop

**Comment by gamenew09** [comment]
Seems to be fixed.

**Comment by gamenew09** [comment]
Needed to set the volume of the music that loops to 0 to "stop" it. This might cause a huge problem when we are playing a whole lot of sounds that are at volume 0.
